from typing import List, Dict


def get_training_data() -> List[Dict[str, str]]:
    return [
        # ── TAXABLE INCOME: freelance_income ──
        {"text": "UPWORK PAYMENT PROJECT COMPLETION INV 2341", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PAYONEER TRANSFER USD 850.00 REF PAY2024", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FIVERR WITHDRAWAL TO BANK ACCOUNT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "CLIENT PAYMENT WEB DESIGN PROJECT CHIDINMA OKONKWO", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "WISE TRANSFER GBP 400 FREELANCE WRITING", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "CONSULTANCY FEE ADAEZE SOLUTIONS LTD", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "TOPTAL PAYMENT Q3 2024 INVOICE", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FREELANCE WRITING FEE GUARDIAN NEWSPAPERS", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "GRAPHIC DESIGN PROJECT PAYMENT FINAL", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PROFESSIONAL FEE INVOICE 45 SETTLEMENT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "UPWORK HOURLY PAYMENT WEEK ENDING 15 NOV", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PAYONEER USD 1200 WITHDRAWAL PROJECT PAYMENT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FIVERR ORDER COMPLETION PAYMENT EMEKA OKAFOR", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "CLIENT PAYMENT MOBILE APP DEVELOPMENT INVOICE 12", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "TRANSFERWISE PAYMENT GBP 300 FREELANCE SEO", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PROJECT PAYMENT WEBSITE REDESIGN ABIOLA CONSULTING", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "INVOICE PAYMENT INV 2024 0567 TECHSTACK LTD", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PROFESSIONAL FEE DATA ANALYSIS Q4 REPORT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FREELANCE INCOME CONTENT WRITING PULSE NIGERIA", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "CONSULTANCY FEE RISK ASSESSMENT REPORT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "GURU COM PAYMENT PROJECT MILESTONE 3", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FREELANCER COM WITHDRAWAL COMPLETED PROJECT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "REMITTANCE PAYMENT CREATIVE SERVICES USD 500", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "CLIENT PAYMENT SOCIAL MEDIA MANAGEMENT RETAINER", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "TOPTAL CONTRACT PAYMENT BACKEND ENGINEERING", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "UPWORK FIXED PRICE CONTRACT LOGO DESIGN", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PAYONEER WITHDRAWAL GBP 650 DEVELOPMENT PROJECT", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "WISE TRANSFER USD 900 CONTENT STRATEGY", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FIVERR PRO PAYMENT VIDEO EDITING DELIVERED", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "INVOICE SETTLEMENT CHIDI ENGINEERING CONSULTANTS", "category": "taxable_income", "sub_category": "freelance_income"},

        # ── TAXABLE INCOME: salary ──
        {"text": "SALARY PAYMENT NOVEMBER 2024", "category": "taxable_income", "sub_category": "salary"},
        {"text": "MONTHLY PAYROLL CREDIT TECHCORP LTD", "category": "taxable_income", "sub_category": "salary"},
        {"text": "NET PAY OCTOBER 2024 STAFF PAYMENT", "category": "taxable_income", "sub_category": "salary"},
        {"text": "WAGES CREDIT WEEKLY PAYMENT CONSTRUCTION CO", "category": "taxable_income", "sub_category": "salary"},
        {"text": "BASIC PAY DECEMBER 2024 ZENITH STAFFING", "category": "taxable_income", "sub_category": "salary"},
        {"text": "SALARI PAYMENT SEPTEMBER ACCESS MARKETING", "category": "taxable_income", "sub_category": "salary"},
        {"text": "MONTHLY PAY CREDIT HUMAN RESOURCES DEPT", "category": "taxable_income", "sub_category": "salary"},
        {"text": "PAYROLL PROCESSING OCTOBER 2024 NGN", "category": "taxable_income", "sub_category": "salary"},
        {"text": "STAFF PAY MONTHLY EMEKA AND ASSOCIATES", "category": "taxable_income", "sub_category": "salary"},
        {"text": "SALARY NOVEMBER ABIOLA NWACHUKWU PAYMENT", "category": "taxable_income", "sub_category": "salary"},
        {"text": "NET SALARY CREDIT DECEMBER 2024 EMPLOYER", "category": "taxable_income", "sub_category": "salary"},
        {"text": "WAGES PAYMENT BIMONTHLY OLUWASEUN INDUSTRIES", "category": "taxable_income", "sub_category": "salary"},
        {"text": "ANNUAL SALARY ARREARS PAYMENT GOVERNMENT", "category": "taxable_income", "sub_category": "salary"},
        {"text": "PAYROLL CREDIT JANUARY 2024 CHISOM TECH", "category": "taxable_income", "sub_category": "salary"},
        {"text": "STAFF PAYMENT JUNE RETAIL OPERATIONS LTD", "category": "taxable_income", "sub_category": "salary"},

        # ── TAXABLE INCOME: business_income ──
        {"text": "SALES PROCEEDS ELECTRONICS STORE JANUARY", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "BUSINESS INCOME TAILORING SERVICES ABUJA", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "REVENUE CREDIT CATERING SERVICES DECEMBER", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "PROCEEDS FROM SALE OF GOODS MARKET DAY", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "BUSINESS PAYMENT PHOTOGRAPHY SESSION FEE", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "REVENUE FROM HAIR SALON SERVICES WEEKLY", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "SALES INCOME BOUTIQUE CLOSING BALANCE", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "BUSINESS PROCEEDS EVENT PLANNING DEPOSIT", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "PROCEEDS PRINTING SERVICES BULK ORDER", "category": "taxable_income", "sub_category": "business_income"},
        {"text": "REVENUE CREDIT RESTAURANT DAILY SALES", "category": "taxable_income", "sub_category": "business_income"},

        # ── TAXABLE INCOME: crypto_income ──
        {"text": "BINANCE P2P TRANSFER USDT SALE", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "CRYPTO WITHDRAWAL QUIDAX COM", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "BITCOIN SALE PROCEEDS LUNO WALLET", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "USDT P2P BYBIT WITHDRAWAL NGN SETTLEMENT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "ETHEREUM SALE COINBASE CREDIT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "KUCOIN WITHDRAWAL CRYPTO TRADING PROFIT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "BLOCKCHAIN PAYMENT CRYPTO FREELANCE USD", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "BUYCOIN P2P SALE NAIRA RECEIPT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "QUIDAX SELL ORDER BITCOIN NGN CREDIT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "BINANCE SPOT WITHDRAWAL USDT TO NAIRA", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "CRYPTO INCOME PAYMENT DEFI YIELD FARMING", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "P2P TRANSFER USDT RECEIPT LUNO", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "BYBIT FUTURES PROFIT WITHDRAWAL NGN", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "COINBASE SALE ETH INTERNATIONAL PAYMENT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "QUIDAX CRYPTO PROCEEDS OCTOBER 2024", "category": "taxable_income", "sub_category": "crypto_income"},

        # ── TAXABLE INCOME: foreign_income ──
        {"text": "SWIFT CREDIT USD 1200 INTERNATIONAL CLIENT", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "WIRE TRANSFER GBP 800 UK CLIENT PAYMENT", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "INTERNATIONAL TRANSFER EUR 600 PROJECT FEE", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "DOMICILIARY ACCOUNT CREDIT USD 950", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "FOREIGN CURRENCY RECEIPT CAD 400 CONSULTING", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "DOLLAR CREDIT SWIFT TRANSFER US CLIENT", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "DOM ACCOUNT INFLOW GBP CONTRACT PAYMENT", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "SWIFT INWARD REMITTANCE USD 2000 SERVICE FEE", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "INTERNATIONAL WIRE RECEIPT AUD 700 CLIENT", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "FOREIGN INCOME DOMICILIARY USD RECEIPT", "category": "taxable_income", "sub_category": "foreign_income"},

        # ── DEDUCTIBLE EXPENSE: internet ──
        {"text": "MTN DATA SUBSCRIPTION 10GB MONTHLY", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "SPECTRANET INTERNET SUBSCRIPTION AUG 2024", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "AIRTEL BROADBAND MONTHLY PLAN 50GB", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "GLO DATA BUNDLE RENEWAL 20GB PLAN", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "9MOBILE DATA SUBSCRIPTION WEEKLY", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "SWIFT NETWORKS WIFI SUBSCRIPTION MONTHLY", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "SMILE INTERNET MONTHLY PLAN RENEWAL", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "BROADBAND INTERNET SPECTRANET QUARTERLY", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "WIFI SUBSCRIPTION OFFICE USE MTN FIBRE", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "DATA BUNDLE PURCHASE AIRTEL BUSINESS PLAN", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "INTERNET SERVICE PAYMENT CORIS NETWORK", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "MTN BUSINESS DATA PLAN 100GB MONTHLY", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "BROADBAND RENEWAL STARLINK HOME PLAN", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "GLO BROADBAND FIBRE MONTHLY PAYMENT", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "AIRTEL 4G LTE HOME BROADBAND SUBSCRIPTION", "category": "deductible_expense", "sub_category": "internet"},

        # ── DEDUCTIBLE EXPENSE: software ──
        {"text": "ADOBE CREATIVE CLOUD MONTHLY SUBSCRIPTION", "category": "deductible_expense", "sub_category": "software"},
        {"text": "GITHUB PRO ANNUAL SUBSCRIPTION", "category": "deductible_expense", "sub_category": "software"},
        {"text": "NOTION TEAM PLAN SUBSCRIPTION", "category": "deductible_expense", "sub_category": "software"},
        {"text": "FIGMA PROFESSIONAL PLAN ANNUAL", "category": "deductible_expense", "sub_category": "software"},
        {"text": "CANVA PRO SUBSCRIPTION MONTHLY PAYMENT", "category": "deductible_expense", "sub_category": "software"},
        {"text": "ZOOM BUSINESS PLAN MONTHLY", "category": "deductible_expense", "sub_category": "software"},
        {"text": "SLACK PRO WORKSPACE SUBSCRIPTION", "category": "deductible_expense", "sub_category": "software"},
        {"text": "MICROSOFT 365 ANNUAL BUSINESS PLAN", "category": "deductible_expense", "sub_category": "software"},
        {"text": "JETBRAINS ALL PRODUCTS PACK ANNUAL", "category": "deductible_expense", "sub_category": "software"},
        {"text": "DIGITALOCEAN MONTHLY SERVER INVOICE", "category": "deductible_expense", "sub_category": "software"},
        {"text": "AWS MONTHLY USAGE INVOICE EC2 S3", "category": "deductible_expense", "sub_category": "software"},
        {"text": "GOOGLE WORKSPACE BUSINESS STARTER MONTHLY", "category": "deductible_expense", "sub_category": "software"},
        {"text": "NETLIFY PRO PLAN HOSTING MONTHLY", "category": "deductible_expense", "sub_category": "software"},
        {"text": "VERCEL PRO PLAN MONTHLY PAYMENT", "category": "deductible_expense", "sub_category": "software"},
        {"text": "NAMECHEAP DOMAIN RENEWAL ANNUAL", "category": "deductible_expense", "sub_category": "software"},
        {"text": "HEROKU DYNO MONTHLY USAGE PAYMENT", "category": "deductible_expense", "sub_category": "software"},
        {"text": "GODADDY DOMAIN REGISTRATION ANNUAL", "category": "deductible_expense", "sub_category": "software"},
        {"text": "GSUITE SUBSCRIPTION BUSINESS PLUS PLAN", "category": "deductible_expense", "sub_category": "software"},
        {"text": "OFFICE 365 SUBSCRIPTION ANNUAL PAYMENT", "category": "deductible_expense", "sub_category": "software"},
        {"text": "ADOBE PHOTOSHOP MONTHLY PLAN RENEWAL", "category": "deductible_expense", "sub_category": "software"},

        # ── DEDUCTIBLE EXPENSE: equipment ──
        {"text": "LAPTOP PURCHASE COMPUTER VILLAGE IKEJA", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "IPHONE 15 PRO PURCHASE JUMIA NIGERIA", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "MACBOOK PRO M3 PURCHASE SLOT NIGERIA", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "DELL XPS LAPTOP PURCHASE COMPUTER SHOP", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "HP LAPTOP PURCHASE BUSINESS USE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "MONITOR PURCHASE LG 27 INCH ULTRAWIDE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "KEYBOARD MECHANICAL LOGITECH PURCHASE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "PHONE PURCHASE SAMSUNG S24 WORK DEVICE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "COMPUTER HARDWARE UPGRADE RAM SSD", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "GADGET PURCHASE SMART TABLET WORK USE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "EXTERNAL HARD DRIVE BACKUP DEVICE PURCHASE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "WEBCAM PURCHASE LOGITECH C920 HOME OFFICE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "MICROPHONE PURCHASE BLUE YETI PODCAST", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "PRINTER PURCHASE HP LASERJET OFFICE USE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "UPS POWER BACKUP PURCHASE OFFICE EQUIPMENT", "category": "deductible_expense", "sub_category": "equipment"},

        # ── DEDUCTIBLE EXPENSE: utilities ──
        {"text": "IKEDC ELECTRICITY TOKEN PURCHASE 5000", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "EKEDC PREPAID METER TOKEN RECHARGE", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "BEDC ELECTRICITY PAYMENT BENIN ZONE", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "NEPA TOKEN PURCHASE OFFICE ELECTRICITY", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "PHCN ELECTRICITY BILL PAYMENT MONTHLY", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "DISCO ELECTRICITY PREPAID TOKEN RECHARGE", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "DSTV SUBSCRIPTION PREMIUM PACKAGE RENEWAL", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "SHOWMAX SUBSCRIPTION MONTHLY RENEWAL", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "NETFLIX SUBSCRIPTION STANDARD PLAN MONTHLY", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "WATER BILL PAYMENT LAGOS WATER CORPORATION", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "ELECTRICITY TOKEN OFFICE POWER PURCHASE", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "KEDCO ELECTRICITY PAYMENT KANO ZONE", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "IBEDC POWER TOKEN PURCHASE IBADAN", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "PHEDC ELECTRICITY POSTPAID BILL PAYMENT", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "AEDC ELECTRICITY ABUJA MONTHLY PAYMENT", "category": "deductible_expense", "sub_category": "utilities"},

        # ── DEDUCTIBLE EXPENSE: professional_development ──
        {"text": "UDEMY COURSE PAYMENT REACT DEVELOPMENT", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "COURSERA ANNUAL SUBSCRIPTION MACHINE LEARNING", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "PLURALSIGHT TRAINING PLATFORM MONTHLY", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "WORKSHOP PAYMENT DATA SCIENCE BOOTCAMP", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "AWS CERTIFICATION EXAM PAYMENT ONLINE", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "BOOK PURCHASE CLEAN CODE PROGRAMMING", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "CONFERENCE TICKET DEVFEST LAGOS 2024", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "SEMINAR REGISTRATION FEE TAX PLANNING", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "LINKEDIN LEARNING PREMIUM MONTHLY PLAN", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "SKILLSHARE ANNUAL MEMBERSHIP SUBSCRIPTION", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "TRAINING PAYMENT KUBERNETES CERTIFICATION", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "GOOGLE CLOUD CERTIFICATION FEE PAYMENT", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "PROFESSIONAL COURSE PAYMENT UI UX DESIGN", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "MICROSOFT AZURE CERTIFICATION EXAM FEE", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "ONLINE COURSE DIGITAL MARKETING PAYMENT", "category": "deductible_expense", "sub_category": "professional_development"},

        # ── DEDUCTIBLE EXPENSE: pension ──
        {"text": "PENSION CONTRIBUTION ARM PENSIONS OCTOBER", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "NHF DEDUCTION FEDERAL MORTGAGE BANK", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "NHIS PAYMENT NATIONAL HEALTH INSURANCE", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "STANBIC IBTC PENSIONS MONTHLY CONTRIBUTION", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "ARM PENSIONS RSA CONTRIBUTION EMPLOYEE", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "AIICO PENSION MONTHLY DEDUCTION OCTOBER", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "RETIREMENT SAVINGS ACCOUNT CONTRIBUTION PFA", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "PENSION FUND ADMINISTRATOR MONTHLY PAYMENT", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "NHF CONTRIBUTION HOUSING FUND OCTOBER", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "NHIS HEALTH INSURANCE MONTHLY PREMIUM", "category": "deductible_expense", "sub_category": "pension"},

        # ── DEDUCTIBLE EXPENSE: transport ──
        {"text": "UBER TRIP LAGOS ISLAND TO MAINLAND", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "BOLT RIDE SHARE VICTORIA ISLAND CLIENT", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "INDRIVER TRIP PAYMENT ABUJA CBD", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "FUEL PURCHASE TOTAL FILLING STATION LEKKI", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "TRANSPORT PAYMENT BRT LAGOS MONTHLY PASS", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "LOGISTICS PAYMENT DHL COURIER DELIVERY", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "DELIVERY SERVICE PAYMENT FEDEX PACKAGE", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "UBER EATS DELIVERY BUSINESS MEAL CLIENT", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "TAXIFY TRIP PAYMENT WORK COMMUTE", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "FUEL PURCHASE MOBIL STATION OFFICE VISIT", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "BOLT BUSINESS TRIP AIRPORT PICKUP CLIENT", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "UBER BUSINESS ACCOUNT TRIP CONFERENCE", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "GIGGSTER LOGISTICS DELIVERY SERVICE PAYMENT", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "FUEL PURCHASE CAR WORK RELATED TRIPS", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "RIDESHARE PAYMENT CLIENT MEETING COMMUTE", "category": "deductible_expense", "sub_category": "transport"},

        # ── NON-TAXABLE: transfer ──
        {"text": "TRF TO OWN ACCOUNT SAVINGS ZENITH", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "INTERBANK TRANSFER PERSONAL USE GTB", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "TRANSFER FROM OWN SAVINGS ACCOUNT", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "INTRA BANK TRANSFER BETWEEN OWN ACCOUNTS", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "TRF TO SELF SALARY HOLDING ACCOUNT", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "BETWEEN ACCOUNTS TRANSFER PERSONAL", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "INTER ACCOUNT FUND MOVEMENT PERSONAL", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "TRF FROM OWN GTB CURRENT ACCOUNT", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "OWN ACCOUNT TRANSFER ZENITH TO KUDA", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "SAVINGS TRANSFER PERSONAL USE STANBIC", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "INTRABANK SWEEP OWN ACCOUNTS DAILY", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "TRANSFER TO SAVINGS GOAL ACCOUNT", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "INTER ACCOUNT MOVEMENT MONTHLY BUDGET", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "WALLET TRANSFER PERSONAL OPAY TO KUDA", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "BETWEEN PERSONAL ACCOUNTS TRANSFER", "category": "non_taxable", "sub_category": "transfer"},

        # ── NON-TAXABLE: loan ──
        {"text": "LOAN REPAYMENT ZENITH BANK CREDIT FACILITY", "category": "non_taxable", "sub_category": "loan"},
        {"text": "QUICK CREDIT REPAYMENT OCTOBER", "category": "non_taxable", "sub_category": "loan"},
        {"text": "SALARY ADVANCE REPAYMENT NOVEMBER", "category": "non_taxable", "sub_category": "loan"},
        {"text": "CREDIT FACILITY DRAWDOWN BUSINESS LOAN", "category": "non_taxable", "sub_category": "loan"},
        {"text": "OVERDRAFT REPAYMENT MONTHLY INSTALMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "PERSONAL LOAN DISBURSEMENT ACCESS BANK", "category": "non_taxable", "sub_category": "loan"},
        {"text": "EMERGENCY LOAN PALMPAY CREDIT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "KUDA OVERDRAFT REPAYMENT AUTO DEBIT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "FAIRMONEY LOAN REPAYMENT INSTALMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "CARBON LOAN DISBURSEMENT PERSONAL", "category": "non_taxable", "sub_category": "loan"},
        {"text": "OPAY LOAN REPAYMENT WEEKLY INSTALMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "MORTGAGE REPAYMENT FEDERAL MORTGAGE BANK", "category": "non_taxable", "sub_category": "loan"},
        {"text": "CAR LOAN REPAYMENT MONTHLY INSTALMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "CREDIT CARD REPAYMENT MONTHLY PAYMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "STUDENT LOAN REPAYMENT GOVERNMENT SCHEME", "category": "non_taxable", "sub_category": "loan"},

        # ── NON-TAXABLE: refund ──
        {"text": "REVERSAL DUPLICATE TRANSACTION REFUND", "category": "non_taxable", "sub_category": "refund"},
        {"text": "CHARGEBACK DISPUTED TRANSACTION CREDIT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "REFUND OVERPAYMENT UTILITIES CREDIT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "DISPUTE CREDIT REVERSAL CARD PAYMENT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "ONLINE PURCHASE REFUND JUMIA RETURN", "category": "non_taxable", "sub_category": "refund"},
        {"text": "SUBSCRIPTION REFUND CANCELLED SERVICE", "category": "non_taxable", "sub_category": "refund"},
        {"text": "OVERPAYMENT REVERSAL SALARY CREDIT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "PRODUCT RETURN REFUND KONGA CREDIT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "CHARGEBACK FRAUD REVERSAL CARD DISPUTE", "category": "non_taxable", "sub_category": "refund"},
        {"text": "ERRONEOUS DEBIT REVERSAL BANK CREDIT", "category": "non_taxable", "sub_category": "refund"},

        # ── NON-TAXABLE: atm ──
        {"text": "ATM WITHDRAWAL LAGOS ISLAND BRANCH", "category": "non_taxable", "sub_category": "atm"},
        {"text": "CASH WITHDRAWAL OVER THE COUNTER BANK", "category": "non_taxable", "sub_category": "atm"},
        {"text": "POS PURCHASE SHOPRITE IKEJA CITY MALL", "category": "non_taxable", "sub_category": "atm"},
        {"text": "ATM CASH WITHDRAWAL GTB VICTORIA ISLAND", "category": "non_taxable", "sub_category": "atm"},
        {"text": "CASH DEPOSIT OVER THE COUNTER ZENITH", "category": "non_taxable", "sub_category": "atm"},
        {"text": "POS DEBIT ARTISAN RESTAURANT IKOYI", "category": "non_taxable", "sub_category": "atm"},
        {"text": "ATM WITHDRAWAL AIRPORT ROAD BRANCH", "category": "non_taxable", "sub_category": "atm"},
        {"text": "CASH WITHDRAWAL TELLER TRANSACTION BRANCH", "category": "non_taxable", "sub_category": "atm"},
        {"text": "POS PAYMENT CHICKEN REPUBLIC SURULERE", "category": "non_taxable", "sub_category": "atm"},
        {"text": "ATM DISPENSE LEKKI PHASE 1 ZENITH ATM", "category": "non_taxable", "sub_category": "atm"},
        {"text": "CASH WITHDRAWAL INTERSWITCH ATM NETWORK", "category": "non_taxable", "sub_category": "atm"},
        {"text": "POS PURCHASE COLD STONE CREAMERY VI", "category": "non_taxable", "sub_category": "atm"},
        {"text": "ATM WITHDRAWAL DAILY LIMIT KUDA CARD", "category": "non_taxable", "sub_category": "atm"},
        {"text": "CASH WITHDRAWAL ABUJA FCT BRANCH ATM", "category": "non_taxable", "sub_category": "atm"},
        {"text": "POS DEBIT SPAR SUPERMARKET MAITAMA", "category": "non_taxable", "sub_category": "atm"},

        # ── NON-TAXABLE: family/personal ──
        {"text": "FAMILY SUPPORT TRANSFER MONTHLY", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "RENT PAYMENT VICTORIA GARDEN CITY", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "SCHOOL FEES PAYMENT COVENANT UNIVERSITY", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "TITHE PAYMENT WINNERS CHAPEL ACCOUNT", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "GIFT TO FRIEND BIRTHDAY CELEBRATION", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "HOUSE RENT ANNUAL PAYMENT LANDLORD", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "PARENT SUPPORT MONTHLY ALLOWANCE", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "SIBLING SCHOOL FEE CONTRIBUTION", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "PERSONAL SPENDING GROCERY STORE PAYMENT", "category": "non_taxable", "sub_category": "atm"},
        {"text": "FOOD DELIVERY PAYMENT JUMIA FOOD APP", "category": "non_taxable", "sub_category": "atm"},

        # ── NEEDS REVIEW (ambiguous) ──
        {"text": "INFLOW FROM JOHN", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT RECEIVED", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT ALERT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER FROM EMEKA NWOSU", "category": "needs_review", "sub_category": "unknown"},
        {"text": "ONLINE PAYMENT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT ORDER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRF 2024001234", "category": "needs_review", "sub_category": "unknown"},
        {"text": "STANDING ORDER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "MANDATE DEDUCTION", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT FROM CHIDI", "category": "needs_review", "sub_category": "unknown"},
        {"text": "MOBILE TRANSFER RECEIVED", "category": "needs_review", "sub_category": "unknown"},
        {"text": "BANK TRANSFER CREDIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "INWARD TRANSFER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT CREDIT 003456", "category": "needs_review", "sub_category": "unknown"},
        {"text": "ACCOUNT CREDIT REF 78901", "category": "needs_review", "sub_category": "unknown"},
        {"text": "FUND RECEIVED UNKNOWN SOURCE", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER IN 20241108", "category": "needs_review", "sub_category": "unknown"},
        {"text": "INFLOW CREDIT NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT IN REF 0034", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT TRANSACTION NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT TRANSACTION CODE 4521", "category": "needs_review", "sub_category": "unknown"},
        {"text": "OUTWARD TRANSFER 20241025", "category": "needs_review", "sub_category": "unknown"},
        {"text": "UNKNOWN DEBIT ENTRY", "category": "needs_review", "sub_category": "unknown"},
        {"text": "MISC PAYMENT OCTOBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT REF 556677", "category": "needs_review", "sub_category": "unknown"},
        {"text": "FUND TRANSFER INCOMING", "category": "needs_review", "sub_category": "unknown"},
        {"text": "RECEIVED AMOUNT 50000", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT 2024 110 456", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT ENTRY NOVEMBER 2024", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT ENTRY UNKNOWN DESCRIPTION", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER RECEIVED NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT MADE VENDOR UNKNOWN", "category": "needs_review", "sub_category": "unknown"},
        {"text": "ACCOUNT DEBIT REF 112233", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSACTION CREDIT 20241201", "category": "needs_review", "sub_category": "unknown"},
        {"text": "INWARD PAYMENT CREDIT NOVEMBER 8", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT RECEIVED FROM UNKNOWN", "category": "needs_review", "sub_category": "unknown"},
        {"text": "MISCELLANEOUS DEBIT NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT TO VENDOR CODE 77", "category": "needs_review", "sub_category": "unknown"},
        {"text": "UNIDENTIFIED CREDIT ENTRY BANK", "category": "needs_review", "sub_category": "unknown"},
        {"text": "UNEXPLAINED DEBIT BANK STATEMENT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DIRECT CREDIT NOVEMBER 2024", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DIRECT DEBIT NOVEMBER 2024", "category": "needs_review", "sub_category": "unknown"},
        {"text": "UNKOWN PAYMENT FROM ACCOUNT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT ORIGIN UNCLEAR", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER CODE 20241107", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT MADE UNCATEGORIZED", "category": "needs_review", "sub_category": "unknown"},
        {"text": "BENEFICIARY UNKNOWN PAYMENT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT FROM NNAMDI", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT TO BIODUN", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT FUNKE ADEYEMI", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER TUNDE BELLO NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT BLESSING OKONKWO", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT CHINWE EZE PAYMENT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT CHUKWUEMEKA OBI", "category": "needs_review", "sub_category": "unknown"},
        {"text": "FUND FROM ADEWALE JOHNSON", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSFER RECEIVED SEUN LAWAL", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT YUSUF IBRAHIM NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "CREDIT FATIMAH AHMED ACCOUNT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "DEBIT AISHA MUSA PAYMENT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "UNKNOWN PURPOSE PAYMENT CREDIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "TRANSACTION UNKNOWN ORIGIN DEBIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "BANK DEBIT NO DESCRIPTION", "category": "needs_review", "sub_category": "unknown"},
        {"text": "ACCOUNT CREDIT NO NARRATION", "category": "needs_review", "sub_category": "unknown"},
        {"text": "ELECTRONIC FUNDS TRANSFER INCOMING", "category": "needs_review", "sub_category": "unknown"},
        {"text": "EFT CREDIT NOVEMBER 2024", "category": "needs_review", "sub_category": "unknown"},
        {"text": "NEFT TRANSFER IN NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "RTGS PAYMENT RECEIVED", "category": "needs_review", "sub_category": "unknown"},
        {"text": "NIPSS PAYMENT CREDIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "NIBSS CREDIT NOVEMBER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "INTERBANK SETTLEMENT CREDIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "PAYMENT CLEARING CREDIT", "category": "needs_review", "sub_category": "unknown"},
        {"text": "BANK CREDIT CLEARING NOVEMBER", "category": "needs_review", "sub_category": "unknown"},

        # Additional training samples for better coverage
        {"text": "UPWORK CONTRACT MILESTONE PAYMENT INV 1890", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "PAYONEER USD 2000 QUARTERLY FREELANCE", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "FIVERR SELLER PAYMENT WITHDRAWAL NOVEMBER", "category": "taxable_income", "sub_category": "freelance_income"},
        {"text": "SALARY CREDIT DECEMBER 2024 EMPLOYER", "category": "taxable_income", "sub_category": "salary"},
        {"text": "MONTHLY SALARY PAYMENT CHINEDU SYSTEMS", "category": "taxable_income", "sub_category": "salary"},
        {"text": "BINANCE CRYPTO SALE P2P NGN RECEIPT", "category": "taxable_income", "sub_category": "crypto_income"},
        {"text": "SWIFT PAYMENT USD INWARD REMITTANCE", "category": "taxable_income", "sub_category": "foreign_income"},
        {"text": "MTN 4G DATA MONTHLY SUBSCRIPTION", "category": "deductible_expense", "sub_category": "internet"},
        {"text": "ADOBE ILLUSTRATOR MONTHLY SUBSCRIPTION", "category": "deductible_expense", "sub_category": "software"},
        {"text": "LAPTOP HP PROBOOK PURCHASE STORE", "category": "deductible_expense", "sub_category": "equipment"},
        {"text": "ELECTRICITY TOKEN PURCHASE 10000 IKEDC", "category": "deductible_expense", "sub_category": "utilities"},
        {"text": "UDEMY PYTHON PROGRAMMING COURSE PAYMENT", "category": "deductible_expense", "sub_category": "professional_development"},
        {"text": "PENSION ARM RSA CONTRIBUTION MONTHLY", "category": "deductible_expense", "sub_category": "pension"},
        {"text": "UBER TRIP CLIENT OFFICE LEKKI", "category": "deductible_expense", "sub_category": "transport"},
        {"text": "TRF TO OWN SAVINGS ACCOUNT UBA", "category": "non_taxable", "sub_category": "transfer"},
        {"text": "PERSONAL LOAN PALMPAY REPAYMENT", "category": "non_taxable", "sub_category": "loan"},
        {"text": "REFUND OVERPAYMENT UTILITY CREDIT", "category": "non_taxable", "sub_category": "refund"},
        {"text": "ATM CASH WITHDRAWAL ZENITH BANK", "category": "non_taxable", "sub_category": "atm"},
        {"text": "PAYMENT FROM UNKNOWN SENDER", "category": "needs_review", "sub_category": "unknown"},
        {"text": "MISC CREDIT NOVEMBER 12", "category": "needs_review", "sub_category": "unknown"},
    ]
